In [1]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_set = pd.read_csv('2018_accidents_vehicles_gu_bcn_.csv',sep = ",")
data_set
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

data_set.iloc[0,:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19079 entries, 0 to 19078
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Codi_expedient            19079 non-null  object
 1   Codi_districte            19079 non-null  int64
 2   Nom_districte             19079 non-null  object
 3   Codi_barri                19079 non-null  int64
 4   Nom_barri                 19079 non-null  object
 5   Codi_carrer               19079 non-null  int64
 6   Nom_carrer                19079 non-null  object
 7   Num_postal                5144 non-null   object
 8   Descripcio_dia_setmana    19079 non-null  object
 9   Dia_setmana               19079 non-null  object
 10  Descripcio_tipus_dia      19079 non-null  object
 11  Any                       19079 non-null  int64
 12  Mes_any                   19079 non-null  int64
 13  Nom_mes                   19079 non-null  object
 14  Dia_mes                   19079 non-null  int64
 15  Hora_dia                  19079 non-null  int64
 16  Descripcio_torn           19079 non-null  object
 17  Descripcio_causa_vianant  19079 non-null  object
 18  Descripcio_tipus_vehicle  19079 non-null  object
 19  Descripcio_model          19079 non-null  object
 20  Descripcio_marca          19079 non-null  object
 21  Descripcio_color          19079 non-null  object
 22  Descripcio_carnet         19079 non-null  object
 23  Antiguitat_carnet         19079 non-null  object
 24  Coordenada_UTM_X          19079 non-null  float64
 25  Coordenada_UTM_Y          19079 non-null  float64
 26  Longitud                  19079 non-null  float64
 27  Latitud                   19079 non-null  float64
dtypes: float64(4), int64(7), object(17)
memory usage: 4.1+ MB
There are this number of expedients 19079
9920

Codi_expedient                                                2018S007344
Codi_districte                                                              1
Nom_districte                                                    Ciutat Vella
Codi_barri                                                                  1
Nom_barri                                                            el Raval
Codi_carrer                                                            269108
Nom_carrer                  Rambla                                        ...
Num_postal                                                                  1
Descripcio_dia_setmana                                               Diumenge
Dia_setmana                                                                Dg
Descripcio_tipus_dia                                                  Laboral
Any                                                                      2018
Mes_any                                                                     9
Nom_mes                                                              Setembre
Dia_mes                                                                    30
Hora_dia                                                                    0
Descripcio_torn                                                           Nit
Descripcio_causa_vianant                             No és causa del  vianant
Descripcio_tipus_vehicle                                              Turisme
Descripcio_model                                                      CORDOBA
Descripcio_marca                                                         SEAT
Descripcio_color                                                        Blanc
Descripcio_carnet                                                           B
Antiguitat_carnet                                                           5
Coordenada_UTM_X                                                     431228.3
Coordenada_UTM_Y                                                   4581110.84
Longitud                                                             2.176455
Latitud                                                             41.376735
Name: 0, dtype: object

In [3]:
data_set = pd.read_csv('2019_accidents_vehicles_gu_bcn_.csv',sep = ",")
data_set
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

data_set.iloc[0,:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19037 entries, 0 to 19036
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          19025 non-null  object
 1   Codi_districte            19037 non-null  int64
 2   Nom_districte             19037 non-null  object
 3   Codi_barri                19037 non-null  int64
 4   Nom_barri                 19037 non-null  object
 5   Codi_carrer               19037 non-null  int64
 6   Nom_carrer                19021 non-null  object
 7   Num_postal                5213 non-null   object
 8   Descripcio_dia_setmana    19037 non-null  object
 9   Dia_setmana               19037 non-null  object
 10  Descripcio_tipus_dia      19037 non-null  object
 11  NK_Any                    19037 non-null  int64
 12  Mes_any                   19037 non-null  int64
 13  Nom_mes                   19037 non-null  object
 14  Dia_mes                   19037 non-null  int64
 15  Hora_dia                  19037 non-null  int64
 16  Descripcio_torn           18881 non-null  object
 17  Descripcio_causa_vianant  19037 non-null  object
 18  Descripcio_tipus_vehicle  19025 non-null  object
 19  Descripcio_model          19024 non-null  object
 20  Descripcio_marca          19025 non-null  object
 21  Descripcio_color          19025 non-null  object
 22  Descripcio_carnet         19025 non-null  object
 23  Antiguitat_carnet         19025 non-null  object
 24  Coordenada_UTM_X          19037 non-null  float64
 25  Coordenada_UTM_Y          19037 non-null  float64
 26  Longitud                  19037 non-null  float64
 27  Latitud                   19037 non-null  float64
dtypes: float64(4), int64(7), object(17)
memory usage: 4.1+ MB
There are this number of expedients 19037
10013

Numero_expedient                                              2019S005075
Codi_districte                                                             -1
Nom_districte                                                      Desconegut
Codi_barri                                                                 -1
Nom_barri                                                          Desconegut
Codi_carrer                                                                -1
Nom_carrer                  Comte d'Urgell / Roma                         ...
Num_postal                                                                NaN
Descripcio_dia_setmana                                                 Dijous
Dia_setmana                                                                Dj
Descripcio_tipus_dia                                                  Laboral
NK_Any                                                                   2019
Mes_any                                                                     6
Nom_mes                                                                  Juny
Dia_mes                                                                    27
Hora_dia                                                                   18
Descripcio_torn                                                         Tarda
Descripcio_causa_vianant                             No és causa del  vianant
Descripcio_tipus_vehicle                                            Bicicleta
Descripcio_model                                                   Desconegut
Descripcio_marca                                                   Desconegut
Descripcio_color                                                   Desconegut
Descripcio_carnet                                                  Desconegut
Antiguitat_carnet                                                  Desconegut
Coordenada_UTM_X                                                    429393.43
Coordenada_UTM_Y                                                   4582076.68
Longitud                                                             2.154311
Latitud                                                             41.385295
Name: 0, dtype: object

In [4]:
data_set = pd.read_csv('2020_accidents_vehicles_gu_bcn.csv',sep = ",")
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

data_set.iloc[0,:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11699 entries, 0 to 11698
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          11699 non-null  object
 1   Codi_districte            11699 non-null  int64
 2   Nom_districte             11699 non-null  object
 3   Codi_barri                11699 non-null  int64
 4   Nom_barri                 11699 non-null  object
 5   Codi_carrer               11699 non-null  int64
 6   Nom_carrer                11699 non-null  object
 7   Num_postal                11699 non-null  object
 8   Descripcio_dia_setmana    11699 non-null  object
 9   Dia_setmana               11699 non-null  object
 10  Descripcio_tipus_dia      11699 non-null  object
 11  NK_Any                    11699 non-null  int64
 12  Mes_any                   11699 non-null  int64
 13  Nom_mes                   11699 non-null  object
 14  Dia_mes                   11699 non-null  int64
 15  Hora_dia                  11699 non-null  int64
 16  Descripcio_torn           11699 non-null  object
 17  Descripcio_causa_vianant  11699 non-null  object
 18  Descripcio_tipus_vehicle  11699 non-null  object
 19  Descripcio_model          11698 non-null  object
 20  Descripcio_marca          11699 non-null  object
 21  Descripcio_color          11699 non-null  object
 22  Descripcio_carnet         11699 non-null  object
 23  Antiguitat_carnet         11699 non-null  object
 24  Coordenada_UTM_X          11699 non-null  float64
 25  Coordenada_UTM_Y          11699 non-null  float64
 26  Latitud                   11699 non-null  float64
 27  Longitud                  11699 non-null  float64
dtypes: float64(4), int64(7), object(17)
memory usage: 2.5+ MB
There are this number of expedients 11699
6257

Numero_expedient                     2020S000001
Codi_districte                                     7
Nom_districte                         Horta-Guinardó
Codi_barri                                        36
Nom_barri                       la Font d'en Fargues
Codi_carrer                                   194406
Nom_carrer                                  Maragall
Num_postal                                 0353 0355
Descripcio_dia_setmana                      Dimecres
Dia_setmana                                       Dc
Descripcio_tipus_dia                         Laboral
NK_Any                                          2020
Mes_any                                            1
Nom_mes                                        Gener
Dia_mes                                            1
Hora_dia                                           0
Descripcio_torn                                  Nit
Descripcio_causa_vianant    No és causa del  vianant
Descripcio_tipus_vehicle                     Turisme
Descripcio_model               C4 CACTUS BLUEHDI 100
Descripcio_marca                             CITROEN
Descripcio_color                          Desconegut
Descripcio_carnet                                  B
Antiguitat_carnet                                  4
Coordenada_UTM_X                           430501.45
Coordenada_UTM_Y                          4586751.53
Latitud                                    41.427474
Longitud                                    2.167116
Name: 0, dtype: object

In [5]:
data_set = pd.read_csv('2021_accidents_vehicles_gu_bcn.csv',sep = ",")
data_set
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

data_set.iloc[0,:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14348 entries, 0 to 14347
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          14343 non-null  object
 1   Codi_districte            14348 non-null  int64
 2   Nom_districte             14348 non-null  object
 3   Codi_barri                14348 non-null  int64
 4   Nom_barri                 14348 non-null  object
 5   Codi_carrer               14348 non-null  int64
 6   Nom_carrer                14323 non-null  object
 7   Num_postal                14314 non-null  object
 8   Descripcio_dia_setmana    14348 non-null  object
 9   NK_Any                    14348 non-null  int64
 10  Mes_any                   14348 non-null  int64
 11  Nom_mes                   14348 non-null  object
 12  Dia_mes                   14348 non-null  int64
 13  Hora_dia                  14348 non-null  int64
 14  Descripcio_torn           14348 non-null  object
 15  Descripcio_causa_vianant  14348 non-null  object
 16  Descripcio_tipus_vehicle  14343 non-null  object
 17  Descripcio_model          14341 non-null  object
 18  Descripcio_marca          14343 non-null  object
 19  Descripcio_color          14343 non-null  object
 20  Descripcio_carnet         14343 non-null  object
 21  Antiguitat_carnet         14343 non-null  object
 22  Coordenada_UTM_X_ED50     14348 non-null  float64
 23  Coordenada_UTM_Y_ED50     14348 non-null  float64
 24  Longitud_WGS84            14297 non-null  float64
 25  Latitud_WGS84             14297 non-null  float64
dtypes: float64(4), int64(7), object(15)
memory usage: 2.8+ MB
There are this number of expedients 14348
7647

Numero_expedient                                              2021S000858
Codi_districte                                                             -1
Nom_districte                                                      Desconegut
Codi_barri                                                                 -1
Nom_barri                                                          Desconegut
Codi_carrer                                                                -1
Nom_carrer                  Arístides Maillol                             ...
Num_postal                                                         6-18
Descripcio_dia_setmana                                                 Dijous
NK_Any                                                                   2021
Mes_any                                                                     2
Nom_mes                                                                Febrer
Dia_mes                                                                    18
Hora_dia                                                                   21
Descripcio_torn                                                         Tarda
Descripcio_causa_vianant                             No és causa del  vianant
Descripcio_tipus_vehicle                                           Ciclomotor
Descripcio_model                                       LIBERTY 50 4T DELIVERY
Descripcio_marca                                                      PIAGGIO
Descripcio_color                                                   Desconegut
Descripcio_carnet                                                          AM
Antiguitat_carnet                                                          15
Coordenada_UTM_X_ED50                                                    -1.0
Coordenada_UTM_Y_ED50                                                    -1.0
Longitud_WGS84                                                            NaN
Latitud_WGS84                                                             NaN
Name: 0, dtype: object

In [6]:
data_set = pd.read_csv('2022_accidents_vehicles_gu_bcn.csv',sep = ",")
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

data_set.iloc[0,:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14906 entries, 0 to 14905
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          14901 non-null  object
 1   Codi_districte            14906 non-null  int64
 2   Nom_districte             14906 non-null  object
 3   Codi_barri                14906 non-null  int64
 4   Nom_barri                 14906 non-null  object
 5   Codi_carrer               14906 non-null  int64
 6   Nom_carrer                14890 non-null  object
 7   Num_postal                14799 non-null  object
 8   Descripcio_dia_setmana    14906 non-null  object
 9   NK_Any                    14906 non-null  int64
 10  Mes_any                   14906 non-null  int64
 11  Nom_mes                   14906 non-null  object
 12  Dia_mes                   14906 non-null  int64
 13  Hora_dia                  14906 non-null  int64
 14  Descripcio_torn           14906 non-null  object
 15  Descripcio_causa_vianant  14906 non-null  object
 16  Descripcio_tipus_vehicle  14901 non-null  object
 17  Descripcio_model          14901 non-null  object
 18  Descripcio_marca          14901 non-null  object
 19  Descripcio_color          14901 non-null  object
 20  Descripcio_carnet         14901 non-null  object
 21  Antiguitat_carnet         14901 non-null  object
 22  Coordenada_UTM_X_ED50     14891 non-null  float64
 23  Coordenada_UTM_Y_ED50     14891 non-null  float64
 24  Longitud                  14891 non-null  float64
 25  Latitud                   14891 non-null  float64
dtypes: float64(4), int64(7), object(15)
memory usage: 3.0+ MB
There are this number of expedients 14906
7985

Numero_expedient                                              2022S000792
Codi_districte                                                             -1
Nom_districte                                                      Desconegut
Codi_barri                                                                 -1
Nom_barri                                                          Desconegut
Codi_carrer                                                                -1
Nom_carrer                  Elisabeth Eidenbenz                           ...
Num_postal                                                         8-24
Descripcio_dia_setmana                                                 Dijous
NK_Any                                                                   2022
Mes_any                                                                     2
Nom_mes                                                                Febrer
Dia_mes                                                                    10
Hora_dia                                                                    8
Descripcio_torn                                                          Matí
Descripcio_causa_vianant                             No és causa del  vianant
Descripcio_tipus_vehicle                                                 Taxi
Descripcio_model                                            TOYOTA PRIUS PLUS
Descripcio_marca                                                       TOYOTA
Descripcio_color                                                   Negre/Groc
Descripcio_carnet                                                           B
Antiguitat_carnet                                                          20
Coordenada_UTM_X_ED50                                               426794.73
Coordenada_UTM_Y_ED50                                              4581925.76
Longitud                                                             2.123343
Latitud                                                             41.383684
Name: 0, dtype: object