In [8]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
data_set = pd.read_csv('2018_accidents_causes_gu_bcn_.csv',sep = ",")
data_set
data_set.info()
data_set.describe()
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9926 entries, 0 to 9925
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          9926 non-null   object
 1   Codi_districte            9926 non-null   int64
 2   Nom_districte             9926 non-null   object
 3   Codi_barri                9926 non-null   int64
 4   Nom_barri                 9926 non-null   object
 5   Codi_carrer               9926 non-null   int64
 6   Nom_carrer                9926 non-null   object
 7   Num_postal                5132 non-null   object
 8   Descripcio_dia_setmana    9926 non-null   object
 9   Dia_setmana               9926 non-null   object
 10  Descripcio_tipus_dia      9926 non-null   object
 11  Any                       9926 non-null   int64
 12  Mes_any                   9926 non-null   int64
 13  Nom_mes                   9926 non-null   object
 14  Dia_mes                   9926 non-null   int64
 15  Hora_dia                  9926 non-null   int64
 16  Descripcio_torn           9926 non-null   object
 17  Descripcio_causa_mediata  9926 non-null   object
 18  Coordenada_UTM_X          9926 non-null   float64
 19  Coordenada_UTM_Y          9926 non-null   float64
 20  Longitud                  9926 non-null   float64
 21  Latitud                   9926 non-null   float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9926 entries, 0 to 9925
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          9926 non-null   object
 1   Codi_districte            9926 non-null   int64
 2   Nom_districte             9926 non-null   object
 3   Codi_barri                9926 non-null   int64
 4   Nom_barri                 9926 non-null   object
 5   Codi_carrer               9926 non-null   int64
 6   Nom_carrer                9926 non-null   object
 7   Num_postal                5132 non-null   object
 8   Descripcio_dia_setmana    9926 non-null   object
 9   Dia_setmana               9926 non-null   object
 10  Descripcio_tipus_dia      9926 non-null   object
 11  Any                       9926 non-null   int64
 12  Mes_any                   9926 non-null   int64
 13  Nom_mes                   9926 non-null   object
 14  Dia_mes                   9926 non-null   int64
 15  Hora_dia                  9926 non-null   int64
 16  Descripcio_torn           9926 non-null   object
 17  Descripcio_causa_mediata  9926 non-null   object
 18  Coordenada_UTM_X          9926 non-null   float64
 19  Coordenada_UTM_Y          9926 non-null   float64
 20  Longitud                  9926 non-null   float64
 21  Latitud                   9926 non-null   float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.7+ MB
There are this number of expedients 9926
9926

In [10]:
data_set = pd.read_csv('2019_accidents_causes_gu_bcn_.csv',sep = ",")
data_set
data_set.info()
data_set.describe()
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10028 entries, 0 to 10027
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          10028 non-null  object
 1   Codi_districte            10028 non-null  int64
 2   Nom_districte             10028 non-null  object
 3   Codi_barri                10028 non-null  int64
 4   Nom_barri                 10028 non-null  object
 5   Codi_carrer               10028 non-null  int64
 6   Nom_carrer                10028 non-null  object
 7   Num_postal                10028 non-null  object
 8   Descripcio_dia_setmana    10028 non-null  object
 9   Dia_setmana               10028 non-null  object
 10  Descripcio_tipus_dia      10028 non-null  object
 11  NK_Any                    10028 non-null  int64
 12  Mes_any                   10028 non-null  int64
 13  Nom_mes                   10028 non-null  object
 14  Dia_mes                   10028 non-null  int64
 15  Hora_dia                  10028 non-null  int64
 16  Descripcio_torn           10028 non-null  object
 17  Descripcio_causa_mediata  10028 non-null  object
 18  Coordenada_UTM_X          10028 non-null  float64
 19  Coordenada_UTM_Y          10028 non-null  float64
 20  Longitud                  10028 non-null  float64
 21  Latitud                   10028 non-null  float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10028 entries, 0 to 10027
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          10028 non-null  object
 1   Codi_districte            10028 non-null  int64
 2   Nom_districte             10028 non-null  object
 3   Codi_barri                10028 non-null  int64
 4   Nom_barri                 10028 non-null  object
 5   Codi_carrer               10028 non-null  int64
 6   Nom_carrer                10028 non-null  object
 7   Num_postal                10028 non-null  object
 8   Descripcio_dia_setmana    10028 non-null  object
 9   Dia_setmana               10028 non-null  object
 10  Descripcio_tipus_dia      10028 non-null  object
 11  NK_Any                    10028 non-null  int64
 12  Mes_any                   10028 non-null  int64
 13  Nom_mes                   10028 non-null  object
 14  Dia_mes                   10028 non-null  int64
 15  Hora_dia                  10028 non-null  int64
 16  Descripcio_torn           10028 non-null  object
 17  Descripcio_causa_mediata  10028 non-null  object
 18  Coordenada_UTM_X          10028 non-null  float64
 19  Coordenada_UTM_Y          10028 non-null  float64
 20  Longitud                  10028 non-null  float64
 21  Latitud                   10028 non-null  float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.7+ MB
There are this number of expedients 10028
10028

In [11]:
data_set = pd.read_csv('2020_accidents_causes_gu_bcn.csv',sep = ",")
data_set.info()
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6261 entries, 0 to 6260
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          6261 non-null   object
 1   Codi_districte            6261 non-null   int64
 2   Nom_districte             6261 non-null   object
 3   Codi_barri                6261 non-null   int64
 4   Nom_barri                 6261 non-null   object
 5   Codi_carrer               6261 non-null   int64
 6   Nom_carrer                6261 non-null   object
 7   Num_postal                6261 non-null   object
 8   Descripcio_dia_setmana    6261 non-null   object
 9   Dia_setmana               6261 non-null   object
 10  Descripcio_tipus_dia      6261 non-null   object
 11  NK_Any                    6261 non-null   int64
 12  Mes_any                   6261 non-null   int64
 13  Nom_mes                   6261 non-null   object
 14  Dia_mes                   6261 non-null   int64
 15  Hora_dia                  6261 non-null   int64
 16  Descripcio_torn           6261 non-null   object
 17  Descripcio_causa_mediata  6261 non-null   object
 18  Coordenada_UTM_X          6261 non-null   float64
 19  Coordenada_UTM_Y          6261 non-null   float64
 20  Longitud                  6261 non-null   float64
 21  Latitud                   6261 non-null   float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6261 entries, 0 to 6260
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          6261 non-null   object
 1   Codi_districte            6261 non-null   int64
 2   Nom_districte             6261 non-null   object
 3   Codi_barri                6261 non-null   int64
 4   Nom_barri                 6261 non-null   object
 5   Codi_carrer               6261 non-null   int64
 6   Nom_carrer                6261 non-null   object
 7   Num_postal                6261 non-null   object
 8   Descripcio_dia_setmana    6261 non-null   object
 9   Dia_setmana               6261 non-null   object
 10  Descripcio_tipus_dia      6261 non-null   object
 11  NK_Any                    6261 non-null   int64
 12  Mes_any                   6261 non-null   int64
 13  Nom_mes                   6261 non-null   object
 14  Dia_mes                   6261 non-null   int64
 15  Hora_dia                  6261 non-null   int64
 16  Descripcio_torn           6261 non-null   object
 17  Descripcio_causa_mediata  6261 non-null   object
 18  Coordenada_UTM_X          6261 non-null   float64
 19  Coordenada_UTM_Y          6261 non-null   float64
 20  Longitud                  6261 non-null   float64
 21  Latitud                   6261 non-null   float64
dtypes: float64(4), int64(7), object(11)
memory usage: 1.1+ MB
There are this number of expedients 6261
6261

In [12]:
data_set = pd.read_csv('2021_accidents_causes_gu_bcn_.csv',sep = ",")
data_set
data_set.info()
data_set.describe()
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)
data_set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7653 entries, 0 to 7652
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          7653 non-null   object
 1   Codi_districte            7653 non-null   int64
 2   Nom_districte             7653 non-null   object
 3   Codi_barri                7653 non-null   int64
 4   Nom_barri                 7653 non-null   object
 5   Codi_carrer               7653 non-null   int64
 6   Nom_carrer                7653 non-null   object
 7   Num_postal                7653 non-null   object
 8   Descripcio_dia_setmana    7653 non-null   object
 9   NK_Any                    7653 non-null   int64
 10  Mes_any                   7653 non-null   int64
 11  Nom_mes                   7653 non-null   object
 12  Dia_mes                   7653 non-null   int64
 13  Hora_dia                  7653 non-null   int64
 14  Descripcio_torn           7653 non-null   object
 15  Descripcio_causa_mediata  7653 non-null   object
 16  Coordenada_UTM_X_ED50     7653 non-null   float64
 17  Coordenada_UTM_Y_ED50     7653 non-null   float64
 18  Longitud_WGS84            7630 non-null   float64
 19  Latitud_WGS84             7630 non-null   float64
dtypes: float64(4), int64(7), object(9)
memory usage: 1.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7653 entries, 0 to 7652
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          7653 non-null   object
 1   Codi_districte            7653 non-null   int64
 2   Nom_districte             7653 non-null   object
 3   Codi_barri                7653 non-null   int64
 4   Nom_barri                 7653 non-null   object
 5   Codi_carrer               7653 non-null   int64
 6   Nom_carrer                7653 non-null   object
 7   Num_postal                7653 non-null   object
 8   Descripcio_dia_setmana    7653 non-null   object
 9   NK_Any                    7653 non-null   int64
 10  Mes_any                   7653 non-null   int64
 11  Nom_mes                   7653 non-null   object
 12  Dia_mes                   7653 non-null   int64
 13  Hora_dia                  7653 non-null   int64
 14  Descripcio_torn           7653 non-null   object
 15  Descripcio_causa_mediata  7653 non-null   object
 16  Coordenada_UTM_X_ED50     7653 non-null   float64
 17  Coordenada_UTM_Y_ED50     7653 non-null   float64
 18  Longitud_WGS84            7630 non-null   float64
 19  Latitud_WGS84             7630 non-null   float64
dtypes: float64(4), int64(7), object(9)
memory usage: 1.2+ MB
There are this number of expedients 7653
7653

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,NK_Any,Mes_any,Nom_mes,Dia_mes,Hora_dia,Descripcio_torn,Descripcio_causa_mediata,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2021S007098,-1,Desconegut,-1,Desconegut,-1,Número 4 Zona Franca ...,85,Dimarts,2021,12,Desembre,7,6,Matí,No hi ha causa mediata,426925.25,4576176.57,2.125596,41.331912
1,2021S005729,-1,Desconegut,-1,Desconegut,-1,Corts ...,65-71,Divendres,2021,10,Octubre,8,14,Tarda,No hi ha causa mediata,426674.42,4581347.85,2.121974,41.378465
2,2021S006593,-1,Desconegut,-1,Desconegut,-1,Joan XXIII ...,3-15,Dimecres,2021,11,Novembre,17,14,Tarda,No hi ha causa mediata,426623.16,4581757.35,2.121311,41.382148
3,2021S004679,10,Sant Martí,64,el Camp de l'Arpa del Clot,346402,Trinxant,0073 0075,Dimarts,2021,8,Agost,24,16,Tarda,No hi ha causa mediata,431951.08,4585370.32,2.184619,41.415158
4,2021S000960,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria,0336 0336,Dimecres,2021,2,Febrer,24,16,Tarda,No hi ha causa mediata,431913.59,4585555.55,2.184149,41.416823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7648,2021S005522,8,Nou Barris,45,Porta,351901,Valldaura,0276X0276X,Dilluns,2021,10,Octubre,4,7,Matí,No hi ha causa mediata,431753.58,4588038.03,2.181955,41.439168
7649,2021S005697,8,Nou Barris,45,Porta,256401,Pintor Alsamora,0002 0002,Dimarts,2021,10,Octubre,12,0,Nit,No hi ha causa mediata,431788.20,4587509.78,2.182429,41.434414
7650,2021S006071,8,Nou Barris,45,Porta,351901,Valldaura,0294 0294,Dimecres,2021,10,Octubre,27,10,Matí,No hi ha causa mediata,431927.43,4588064.59,2.184032,41.439422
7651,2021S003725,8,Nou Barris,44,Vilapicina i la Torre Llobeta,24304,Arnau d'Oms,0034 0036,Dilluns,2021,7,Juliol,5,14,Tarda,No hi ha causa mediata,431370.38,4587010.59,2.177485,41.429882
7652,2021S002530,8,Nou Barris,45,Porta,282650,Rio de Janeiro,0017 0019,Divendres,2021,5,Maig,14,17,Tarda,No hi ha causa mediata,431633.66,4587255.68,2.180608,41.432112

In [13]:
data_set = pd.read_csv('2022_accidents_causes_gu_bcn_.csv',sep = ",")
data_set.info()
numer_exp=data_set.iloc[:,0]
numer_exp1= len(numer_exp)
print('There are this number of expedients'+' '+str(numer_exp1))
real_people= numer_exp.drop_duplicates()
real=len(real_people)
print(real)
data_set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7989 entries, 0 to 7988
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Numero_expedient          7989 non-null   object
 1   Codi_districte            7989 non-null   int64
 2   Nom_districte             7989 non-null   object
 3   Codi_barri                7989 non-null   int64
 4   Nom_barri                 7989 non-null   object
 5   Codi_carrer               7989 non-null   int64
 6   Nom_carrer                7988 non-null   object
 7   Num_postal                7987 non-null   object
 8   Descripcio_dia_setmana    7989 non-null   object
 9   NK_Any                    7989 non-null   int64
 10  Mes_any                   7989 non-null   int64
 11  Nom_mes                   7989 non-null   object
 12  Dia_mes                   7989 non-null   int64
 13  Hora_dia                  7989 non-null   int64
 14  Descripcio_torn           7989 non-null   object
 15  Descripcio_causa_mediata  7989 non-null   object
 16  Coordenada_UTM_X_ED50     7989 non-null   float64
 17  Coordenada_UTM_Y_ED50     7989 non-null   float64
 18  Longitud                  7989 non-null   float64
 19  Latitud                   7989 non-null   float64
dtypes: float64(4), int64(7), object(9)
memory usage: 1.2+ MB
There are this number of expedients 7989
7989

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,NK_Any,Mes_any,Nom_mes,Dia_mes,Hora_dia,Descripcio_torn,Descripcio_causa_mediata,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud,Latitud
0,2022S007102,-1,Desconegut,-1,Desconegut,-1,Prim ...,160,Dissabte,2022,11,Novembre,19,21,Tarda,Alcoholèmia,433936.08,4585919.91,2.208309,41.420277
1,2022S006766,-1,Desconegut,-1,Desconegut,-1,Foc ...,101-139,Dilluns,2022,11,Novembre,7,10,Matí,No hi ha causa mediata,428815.19,4579271.99,2.147817,41.359963
2,2022S007861,-1,Desconegut,-1,Desconegut,-1,Jordi Girona ...,18-26,Dijous,2022,12,Desembre,22,21,Tarda,No hi ha causa mediata,426095.42,4582377.28,2.114925,41.387686
3,2022S006073,-1,Desconegut,-1,Desconegut,-1,A Zona Franca / Número 3 Zona Franca ...,NaN,Dissabte,2022,10,Octubre,8,21,Tarda,Alcoholèmia,428020.43,4576283.26,2.138671,41.332974
4,2022S000440,-1,Desconegut,-1,Desconegut,-1,Corts / Blanca ...,NaN,Dimecres,2022,1,Gener,26,0,Nit,No hi ha causa mediata,426626.85,4581292.09,2.121412,41.377961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7984,2022S004703,8,Nou Barris,44,Vilapicina i la Torre Llobeta,86108,Concepción Arenal / Riera d'Horta ...,0187 0189,Dilluns,2022,8,Agost,1,22,Nit,No hi ha causa mediata,431937.06,4586756.33,2.184295,41.427643
7985,2022S002165,9,Sant Andreu,61,la Sagrera,105701,Dublín / Torroella de Montgrí ...,0017 0017,Dimecres,2022,4,Abril,13,0,Nit,Alcoholèmia,432085.19,4586864.33,2.186056,41.428628
7986,2022S004308,8,Nou Barris,45,Porta,282650,Valldaura ...,0092B0092B,Dijous,2022,7,Juliol,14,10,Matí,No hi ha causa mediata,431806.24,4588046.08,2.182584,41.439248
7987,2022S004988,8,Nou Barris,45,Porta,282650,Rio de Janeiro ...,0055 0055,Divendres,2022,8,Agost,19,8,Matí,No hi ha causa mediata,431605.40,4587751.52,2.180214,41.436578
7988,2022S007042,8,Nou Barris,45,Porta,351901,Valldaura ...,0294 0294,Dijous,2022,11,Novembre,17,17,Tarda,No hi ha causa mediata,431927.43,4588064.59,2.184032,41.439425