In [51]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [52]:
persones=pd.read_csv('Accident_people_2021_2022.csv')
persones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17919 entries, 0 to 17918
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    17919 non-null  int64
 1   File_Num                      17919 non-null  object
 2   District                      17919 non-null  object
 3   Neighbourhood                 17919 non-null  object
 4   Street_name                   17919 non-null  object
 5   Day_name                      17919 non-null  object
 6   year                          17919 non-null  int64
 7   month                         17919 non-null  int64
 8   Month_name                    17919 non-null  object
 9   day                           17919 non-null  int64
 10  Day_shift                     17919 non-null  object
 11  hour                          17919 non-null  int64
 12  Pedestrian_situation          17919 non-null  object
 13  Vehicle_type                  17919 non-null  object
 14  Gender                        17919 non-null  object
 15  Age                           17919 non-null  object
 16  Person_type                   17919 non-null  object
 17  Pedestrian_accident_location  17919 non-null  object
 18  Pedestrian_intention          17919 non-null  object
 19  Driver_intention              17919 non-null  object
 20  Accident_severity             17919 non-null  object
 21  Date                          17919 non-null  object
dtypes: int64(5), object(17)
memory usage: 3.0+ MB

In [53]:
weather=pd.read_csv('data_meteo_estudifinal_2021_2022.csv')
weather = weather.drop(weather.columns[0], axis=1)
weather.rename(columns={'DATA_LECTURA':'Date'},inplace=True)
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       35040 non-null  object
 1   03.TM      35040 non-null  float64
 2   06.HRM     35040 non-null  float64
 3   07.PPT24H  35040 non-null  float64
 4   08.HPA     35040 non-null  float64
 5   09.RS24H   35040 non-null  float64
 6   10.VVM10   35040 non-null  float64
dtypes: float64(6), object(1)
memory usage: 1.9+ MB

In [54]:
persones= persones[persones['Person_type'] == 'Driver']
persones.head()

,Unnamed: 0,File_Num,District,Neighbourhood,Street_name,Day_name,year,month,Month_name,day,...,Pedestrian_situation,Vehicle_type,Gender,Age,Person_type,Pedestrian_accident_location,Pedestrian_intention,Driver_intention,Accident_severity,Date
6,6,2021S003310,Ciutat Vella,el Barri Gòtic,Catalunya,Dijous,2021,6,Juny,17,...,Not pedestrian fault,Vehicle without motor,Men,31,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Assistance,2021-06-17 20:00:00
8,8,2021S001728,Ciutat Vella,la Barceloneta,Marina,Diumenge,2021,4,Abril,4,...,Not known,Vehicle without motor,Women,45,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Hospitalized,2021-04-04 10:00:00
17,17,2021S005721,Eixample,el Fort Pienc,Marina,Dimecres,2021,10,Octubre,13,...,Not pedestrian fault,Other,Women,51,Driver,A la vorera / Andana ...,Desconegut,In itínere,Hospitalized,2021-10-13 08:00:00
31,31,2021S005403,Eixample,l'Antiga Esquerra de l'Eixample,Aragó,Dimecres,2021,9,Setembre,29,...,Not pedestrian fault,Car,Men,71,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Assistance,2021-09-29 09:00:00
39,39,2021S004164,Eixample,Sant Antoni,Comte Borrell,Divendres,2021,7,Juliol,23,...,Not pedestrian fault,Motorcycle,Men,24,Driver,A la vorera / Andana ...,Desconegut,Altres activitats,Hospitalized,2021-07-23 19:00:00

In [55]:
#FROM ALL THE DATA WE ARE JUST GOING TO FOCUS N¡ON THE DRIVERS BECAUSE
#THE PASSANGER OR THE PEDESTRIAN DOESN0T HAVE ANY KIND OF POWER TO NOT BE IN THE SITUATION OR HAVE ANY CONTROL

persones=persones[['Day_shift','Vehicle_type','Gender','Age','Date']]
weather=weather[['Date','03.TM','06.HRM','10.VVM10']]

#JOIN THE DATASETS WITH THE VARIABLE DATE
variables = pd.merge(persones, weather, on='Date', how='left')
variables.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12681 entries, 0 to 12680
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Day_shift     12681 non-null  object
 1   Vehicle_type  12681 non-null  object
 2   Gender        12681 non-null  object
 3   Age           12681 non-null  object
 4   Date          12681 non-null  object
 5   03.TM         12681 non-null  float64
 6   06.HRM        12681 non-null  float64
 7   10.VVM10      12681 non-null  float64
dtypes: float64(3), object(5)
memory usage: 891.6+ KB

In [56]:
#add variable quarter and start studying the different variables
variables['Quarter'] = variables['Date'].apply(lambda x: pd.Timestamp(x).quarter)
variables.head()

,Day_shift,Vehicle_type,Gender,Age,Date,03.TM,06.HRM,10.VVM10,Quarter
0,Afternoon,Vehicle without motor,Men,31,2021-06-17 20:00:00,23.4,97.0,1.1,2
1,Morning,Vehicle without motor,Women,45,2021-04-04 10:00:00,15.9,55.0,2.3,2
2,Morning,Other,Women,51,2021-10-13 08:00:00,19.3,65.0,1.0,4
3,Morning,Car,Men,71,2021-09-29 09:00:00,23.5,64.0,1.4,3
4,Afternoon,Motorcycle,Men,24,2021-07-23 19:00:00,27.7,53.0,0.8,3

In [57]:
# LETS TRANSFORM TO CATHEGORIC THE COLUMN EDAT
#'youth' if their age value is lower than 21, 'young adult' from 21 to 31, 'adult' from 32 to 50, 'old' from 51 /// desconegut(404) -->NOT KNOWN
#transform value desconegut a 404
variables['Age'] = variables['Age'].replace('Desconegut', '404')
def categorize_age(age):
    if int(age) <= 23:
        return 'Young'
    elif int(age) <= 30 and int(age) > 23:
        return 'Young Adult'
    elif int(age) <= 50 and int(age) > 30:
        return 'Adult'
    elif age == '404':
        return 'Not known'
    else:
        return 'Old'

# Apply function to transform ages to categories
variables['Age'] = variables['Age'].apply(categorize_age)

x=variables['Age'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['Age'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Adult' 'Old' 'Young Adult' 'Young' 'Not known']
Adult          46.266067
Young Adult    21.867361
Old            19.888021
Young          11.931236
Not known       0.047315
Name: Age, dtype: float64

In [58]:
#x=variables['03.TM'].unique()
# print(np.sort(x)) the data goes from 3.8 to 34.2
def cat_temp(temp):
    if int(temp) <= 13:
        return 'Very low'
    elif int(temp) <= 17 and int(temp) > 13:
        return 'Low'
    elif int(temp) <= 24 and int(temp) > 17:
        return 'Mild'
    else:
        return 'Hot'
variables['03.TM'] = variables['03.TM'].apply(cat_temp)

x=variables['03.TM'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['03.TM'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Mild' 'Low' 'Hot' 'Very low']
Mild        30.273638
Very low    25.045343
Hot         23.200063
Low         21.480956
Name: 03.TM, dtype: float64

In [59]:
#x=variables['06.HRM'].unique()
#print(np.sort(x)) from 9 percent to 100 percent
def cat_humidity(hum):
    if int(hum) <= 48:
        return 'Low'
    elif int(hum) <= 60 and int(hum) > 48:
        return 'Moderate'
    elif int(hum) <= 75 and int(hum) > 60:
        return 'High'
    else:
        return 'Very high'
variables['06.HRM'] = variables['06.HRM'].apply(cat_humidity)

x=variables['06.HRM'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['06.HRM'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Very high' 'Moderate' 'High' 'Low']
High         39.216150
Moderate     25.234603
Low          19.075783
Very high    16.473464
Name: 06.HRM, dtype: float64

In [60]:
#x=variables['10.VVM10'].unique()
#print(np.sort(x)) from 0 to 8.7
#x=variables['06.HRM'].unique()
#print(np.sort(x)) from 9 percent to 100 percent
def cat_wind(wind):
    if int(wind) <= 1:
        return 'Low'
    elif int(wind) <= 2 and int(wind) > 1:
        return 'Moderate'
    else:
        return 'High'
    
variables['10.VVM10'] = variables['10.VVM10'].apply(cat_wind)

x=variables['10.VVM10'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['10.VVM10'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Low' 'Moderate' 'High']
Low         43.080199
Moderate    30.344610
High        26.575191
Name: 10.VVM10, dtype: float64