In [564]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [565]:
persones=pd.read_csv('Accident_people_2021_2022.csv')
persones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17919 entries, 0 to 17918
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    17919 non-null  int64
 1   File_Num                      17919 non-null  object
 2   District                      17919 non-null  object
 3   Neighbourhood                 17919 non-null  object
 4   Street_name                   17919 non-null  object
 5   Day_name                      17919 non-null  object
 6   year                          17919 non-null  int64
 7   month                         17919 non-null  int64
 8   Month_name                    17919 non-null  object
 9   day                           17919 non-null  int64
 10  Day_shift                     17919 non-null  object
 11  hour                          17919 non-null  int64
 12  Pedestrian_situation          17919 non-null  object
 13  Vehicle_type                  17919 non-null  object
 14  Gender                        17919 non-null  object
 15  Age                           17919 non-null  object
 16  Person_type                   17919 non-null  object
 17  Pedestrian_accident_location  17919 non-null  object
 18  Pedestrian_intention          17919 non-null  object
 19  Driver_intention              17919 non-null  object
 20  Accident_severity             17919 non-null  object
 21  Date                          17919 non-null  object
dtypes: int64(5), object(17)
memory usage: 3.0+ MB

In [566]:
weather=pd.read_csv('data_meteo_estudifinal_2021_2022.csv')
weather = weather.drop(weather.columns[0], axis=1)
weather.rename(columns={'DATA_LECTURA':'Date'},inplace=True)
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       35040 non-null  object
 1   03.TM      35040 non-null  float64
 2   06.HRM     35040 non-null  float64
 3   07.PPT24H  35040 non-null  float64
 4   08.HPA     35040 non-null  float64
 5   09.RS24H   35040 non-null  float64
 6   10.VVM10   35040 non-null  float64
dtypes: float64(6), object(1)
memory usage: 1.9+ MB

In [567]:
persones= persones[persones['Person_type'] == 'Driver']
persones.head()

,Unnamed: 0,File_Num,District,Neighbourhood,Street_name,Day_name,year,month,Month_name,day,...,Pedestrian_situation,Vehicle_type,Gender,Age,Person_type,Pedestrian_accident_location,Pedestrian_intention,Driver_intention,Accident_severity,Date
6,6,2021S003310,Ciutat Vella,el Barri Gòtic,Catalunya,Dijous,2021,6,Juny,17,...,Not pedestrian fault,Vehicle without motor,Men,31,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Assistance,2021-06-17 20:00:00
8,8,2021S001728,Ciutat Vella,la Barceloneta,Marina,Diumenge,2021,4,Abril,4,...,Not known,Vehicle without motor,Women,45,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Hospitalized,2021-04-04 10:00:00
17,17,2021S005721,Eixample,el Fort Pienc,Marina,Dimecres,2021,10,Octubre,13,...,Not pedestrian fault,Other,Women,51,Driver,A la vorera / Andana ...,Desconegut,In itínere,Hospitalized,2021-10-13 08:00:00
31,31,2021S005403,Eixample,l'Antiga Esquerra de l'Eixample,Aragó,Dimecres,2021,9,Setembre,29,...,Not pedestrian fault,Car,Men,71,Driver,A la vorera / Andana ...,Desconegut,Oci i entreteniment,Assistance,2021-09-29 09:00:00
39,39,2021S004164,Eixample,Sant Antoni,Comte Borrell,Divendres,2021,7,Juliol,23,...,Not pedestrian fault,Motorcycle,Men,24,Driver,A la vorera / Andana ...,Desconegut,Altres activitats,Hospitalized,2021-07-23 19:00:00

In [568]:
#FROM ALL THE DATA WE ARE JUST GOING TO FOCUS N¡ON THE DRIVERS BECAUSE
#THE PASSANGER OR THE PEDESTRIAN DOESN0T HAVE ANY KIND OF POWER TO NOT BE IN THE SITUATION OR HAVE ANY CONTROL

persones=persones[['Day_shift','Vehicle_type','Gender','Age','Date']]
weather=weather[['Date','03.TM','06.HRM','10.VVM10']]

#JOIN THE DATASETS WITH THE VARIABLE DATE
variables = pd.merge(persones, weather, on='Date', how='left')
variables.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12681 entries, 0 to 12680
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Day_shift     12681 non-null  object
 1   Vehicle_type  12681 non-null  object
 2   Gender        12681 non-null  object
 3   Age           12681 non-null  object
 4   Date          12681 non-null  object
 5   03.TM         12681 non-null  float64
 6   06.HRM        12681 non-null  float64
 7   10.VVM10      12681 non-null  float64
dtypes: float64(3), object(5)
memory usage: 891.6+ KB

In [569]:
#add variable quarter and start studying the different variables
variables['Quarter'] = variables['Date'].apply(lambda x: pd.Timestamp(x).quarter)
variables.head()

,Day_shift,Vehicle_type,Gender,Age,Date,03.TM,06.HRM,10.VVM10,Quarter
0,Afternoon,Vehicle without motor,Men,31,2021-06-17 20:00:00,23.4,97.0,1.1,2
1,Morning,Vehicle without motor,Women,45,2021-04-04 10:00:00,15.9,55.0,2.3,2
2,Morning,Other,Women,51,2021-10-13 08:00:00,19.3,65.0,1.0,4
3,Morning,Car,Men,71,2021-09-29 09:00:00,23.5,64.0,1.4,3
4,Afternoon,Motorcycle,Men,24,2021-07-23 19:00:00,27.7,53.0,0.8,3

In [570]:
# LETS TRANSFORM TO CATHEGORIC THE COLUMN EDAT
#'youth' if their age value is lower than 21, 'young adult' from 21 to 31, 'adult' from 32 to 50, 'old' from 51 /// desconegut(404) -->NOT KNOWN
#transform value desconegut a 404
variables['Age'] = variables['Age'].replace('Desconegut', '404')
def categorize_age(age):
    if int(age) <= 18:
        return 'Kid'
    elif int(age) <= 30 and int(age) > 18:
        return 'Youth'
    elif int(age) <= 55 and int(age) > 30:
        return 'Adult'
    elif age == '404':
        return 'Not known'
    else:
        return 'Old'

# Apply function to transform ages to categories
variables['Age'] = variables['Age'].apply(categorize_age)

x=variables['Age'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['Age'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Adult' 'Old' 'Youth' 'Kid' 'Not known']
Adult        54.372684
Youth        31.724627
Old          11.781405
Kid           2.073969
Not known     0.047315
Name: Age, dtype: float64

In [571]:
#x=variables['03.TM'].unique()
# print(np.sort(x)) the data goes from 3.8 to 34.2
def cat_temp(temp):
    if int(temp) <= 13:
        return 'Very low'
    elif int(temp) <= 17 and int(temp) > 13:
        return 'Low'
    elif int(temp) <= 24 and int(temp) > 17:
        return 'Mild'
    else:
        return 'Hot'
variables['03.TM'] = variables['03.TM'].apply(cat_temp)

x=variables['03.TM'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['03.TM'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Mild' 'Low' 'Hot' 'Very low']
Mild        30.273638
Very low    25.045343
Hot         23.200063
Low         21.480956
Name: 03.TM, dtype: float64

In [572]:
#x=variables['06.HRM'].unique()
#print(np.sort(x)) from 9 percent to 100 percent
def cat_humidity(hum):
    if int(hum) <= 48:
        return 'Low'
    elif int(hum) <= 60 and int(hum) > 48:
        return 'Moderate'
    elif int(hum) <= 75 and int(hum) > 60:
        return 'High'
    else:
        return 'Very high'
variables['06.HRM'] = variables['06.HRM'].apply(cat_humidity)

x=variables['06.HRM'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['06.HRM'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Very high' 'Moderate' 'High' 'Low']
High         39.216150
Moderate     25.234603
Low          19.075783
Very high    16.473464
Name: 06.HRM, dtype: float64

In [573]:
#x=variables['10.VVM10'].unique()
#print(np.sort(x)) from 0 to 8.7
#x=variables['06.HRM'].unique()
#print(np.sort(x)) from 9 percent to 100 percent
def cat_wind(wind):
    if int(wind) <= 1:
        return 'Low'
    elif int(wind) <= 2 and int(wind) > 1:
        return 'Moderate'
    else:
        return 'High'
    
variables['10.VVM10'] = variables['10.VVM10'].apply(cat_wind)

x=variables['10.VVM10'].unique()
print(x)

# count the frequency of each value in column 'a'
value_counts = variables['10.VVM10'].value_counts()

# calculate the percentage of times each value appears
percentage = (value_counts / len(variables)) * 100
print(percentage)

['Low' 'Moderate' 'High']
Low         43.080199
Moderate    30.344610
High        26.575191
Name: 10.VVM10, dtype: float64

ITERATIVE CLUSTER

In [574]:
from sklearn import preprocessing
from kmodes.kmodes import KModes

# Subset of variables for clustering
subgroup = variables[['Day_shift', 'Vehicle_type', 'Gender', 'Age', '03.TM']]

# Label encoding
le = preprocessing.LabelEncoder()
subgroup_encoded = subgroup.apply(le.fit_transform)
#to create the list to get the percenge of significant clusters
l=[]
# Iterate through cluster numbers
for n_clusters in range(3, 20):
    # Clustering
    km = KModes(n_clusters=n_clusters, init='Cao', n_init=1, verbose=1)
    clusters = km.fit_predict(subgroup_encoded)

    # Combine with original data
    combined = pd.concat([subgroup.reset_index(), pd.DataFrame({'Cluster': clusters})], axis=1).drop('index', axis=1)

    # Create table
    table = pd.DataFrame(columns=range(n_clusters))

    # Fill in table with percentage of instances of each value in each cluster for each variable
    for var in subgroup.columns:
        by_cluster_value = combined.groupby(['Cluster', var]).size()
        percentages = by_cluster_value.groupby(level=0).apply(lambda x: x / x.sum() * 100)
        pivot_table = pd.pivot_table(percentages.reset_index(), index=var, columns='Cluster', values=0, fill_value=0)

        # Fill in table with percentage of instances for each value in each cluster
        for i, col in enumerate(pivot_table.columns):
            values = pivot_table[col].index.tolist()
            pct_values = pivot_table[col].tolist()
            for j, value in enumerate(values):
                table.loc[value, i] = pct_values[j]
        # Add new column with variable names based on index
    table['VARIABLE'] = ''
    for i, index_value in enumerate(table.index.values):
        if index_value in ['Afternoon', 'Morning', 'Night']:
            table.iloc[i, -1] = 'Day_shift'
        elif index_value in subgroup['Vehicle_type'].unique():
            table.iloc[i, -1] = 'Vehicle_type'
        elif index_value in subgroup['Gender'].unique():
            table.iloc[i, -1] = 'Gender'
        elif index_value in subgroup['Age'].unique():
            table.iloc[i, -1] = 'Age'
        else:
            table.iloc[i, -1] = '03.TM'
    table = table.reset_index().rename(columns={'index': 'value'})
    table = table[['VARIABLE'] + list(table.columns[:-1])]
    table = table.set_index('VARIABLE')        

    # Add a new row for the cluster totals
    table.loc['Cluster percentage of drivers'] = 0

    # Calculate the number of instances in each cluster
    cluster_counts = combined['Cluster'].value_counts()

    # Fill in the table with the percentage of instances in each cluster
    for i, count in cluster_counts.items():
        table.loc['Cluster percentage of drivers', i] = count / len(combined) * 100
   
    #table.to_excel(f'table_{n_clusters}_clusters_pas1.xlsx', index=True)

    # Save table to CSV file
    table = table.drop('value', axis=1)
    new_table_2 = pd.DataFrame(index=table.index.unique())
# Iterate over each column (0, 1, 2, 3) and find the highest percentage for each variable
    for col in table.columns:
        col_max = table.groupby(level=0)[col].max()
        new_table_2[col] = col_max
# Add the 'Cluster percentage of drivers' row back to the new DataFrame
    new_table_2.loc['Cluster percentage of drivers'] = table.loc['Cluster percentage of drivers']
# Display the new DataFrame
    #print(new_table_2)
    #new_table_2.to_excel(f'table_{n_clusters}_clusters_pas2.xlsx', index=True)
    new_table_3= new_table_2.loc[new_table_2.index != 'Cluster percentage of drivers'] = (new_table_2.loc[new_table_2.index != 'Cluster percentage of drivers'] >= 75).astype(int)
    new_table_3.loc['number of significant variables'] = new_table_3.sum()
    #new_table_2.to_excel(f'table_{n_clusters}_clusters_pas3.xlsx', index=True)
    #print(new_table_3)  
    new_table_3.loc['Cluster significance'] = new_table_3 .loc['number of significant variables'] / 5
    new_table_3.loc['Cluster significant?'] = new_table_3 .loc['Cluster significance']>=0.5
    new_table_4=new_table_3
    new_table_4.loc['Cluster percentage of drivers'] = table.loc['Cluster percentage of drivers']
    new_table_4.loc['Significant clusters'] = np.nan
# Add a column with the percentage of significant cluster
    new_table_4.loc['Significant clusters' ,'percentage of significant cluster'] = new_table_4.loc['Cluster significant?'].sum() / n_clusters
# Transpose the dataframe back to its original orientation
    l.append(round(new_table_4.loc['Cluster significant?'].sum() / n_clusters,2))
    print(l)
# Print the resulting dataframe
    #new_table_4.to_excel(f'table_{n_clusters}_clusters_pas4.xlsx', index=True)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 22899.0
[0.0]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 21502.0
[0.0, 0.25]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 20389.0
[0.0, 0.25, 0.2]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 702, cost: 18952.0
[0.0, 0.25, 0.2, 0.33]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 702, cost: 17963.0
[0.0, 0.25, 0.2, 0.33, 0.43]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 702, cost: 17151.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 905, cost: 16349.0
Run 1, iteration: 2/100, moves: 228, cost: 16349.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 898, cost: 15803.0
Run 1, iteration: 2/100, moves: 228, cost: 15803.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 782, cost: 15478.0
Run 1, iteration: 2/100, moves: 345, cost: 15478.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 763, cost: 15134.0
Run 1, iteration: 2/100, moves: 345, cost: 15134.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 745, cost: 14512.0
Run 1, iteration: 2/100, moves: 331, cost: 14512.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 460, cost: 14062.0
Run 1, iteration: 2/100, moves: 331, cost: 14062.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 460, cost: 13609.0
Run 1, iteration: 2/100, moves: 331, cost: 13609.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 457, cost: 13096.0
Run 1, iteration: 2/100, moves: 311, cost: 13096.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8, 0.88]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 452, cost: 12952.0
Run 1, iteration: 2/100, moves: 311, cost: 12952.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8, 0.88, 0.88]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 452, cost: 12630.0
Run 1, iteration: 2/100, moves: 311, cost: 12630.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8, 0.88, 0.88, 0.89]
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 452, cost: 12386.0
Run 1, iteration: 2/100, moves: 311, cost: 12386.0
[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8, 0.88, 0.88, 0.89, 0.89]

In [575]:
print(l)

[0.0, 0.25, 0.2, 0.33, 0.43, 0.5, 0.56, 0.7, 0.73, 0.75, 0.77, 0.79, 0.8, 0.88, 0.88, 0.89, 0.89]

In [576]:
print(table)

                                       0          1          2          3  \
VARIABLE
Day_shift                      80.736544  11.133603   6.342495   7.011866
Day_shift                      13.399433  80.769231  87.103594  84.681769
Day_shift                       5.864023   8.097166   6.553911   8.306365
Vehicle_type                    7.195467   6.376518  55.179704   5.501618
Vehicle_type                   83.229462   82.08502  20.084567  31.823085
Vehicle_type                    5.580737    5.97166  17.336152  58.899676
Vehicle_type                    3.994334   5.566802   7.399577    3.77562
Gender                         93.427762   13.05668  94.714588  91.693635
Gender                          0.056657        0.0   0.211416    0.21575
Gender                          6.543909   86.94332   5.073996    8.19849
Age                            83.002833  14.777328  13.319239  88.133765
Age                             1.246459   1.619433   2.114165   3.128371
Age                             7.110482   9.311741  67.653277   1.294498
Age                             8.583569  74.291498  16.701903   7.227616
03.TM                          15.609065   10.62753  68.710359  12.081985
03.TM                          13.399433  15.283401  13.319239  12.405609
03.TM                          59.235127  14.676113   9.936575   8.845739
03.TM                          11.756374  59.412955   8.033827  66.666667
Cluster percentage of drivers  27.836921   7.791184    3.72999   7.310149

                                       4          5          6          7  \
VARIABLE
Day_shift                      28.064147        0.0  93.083573  96.466974
Day_shift                      15.463918  89.259259    3.89049   2.304147
Day_shift                      56.471936  10.740741   3.025937   1.228879
Vehicle_type                    5.841924   7.777778  52.881844  12.135177
Vehicle_type                   77.777778  84.444444  36.023055  75.576037
Vehicle_type                   11.683849        0.0    6.48415   7.680492
Vehicle_type                    4.696449   7.777778   4.610951   4.608295
Gender                         96.105384  84.197531  85.158501  16.743472
Gender                               0.0        0.0        0.0        0.0
Gender                          3.894616  15.802469  14.841499  83.256528
Age                              7.44559  69.259259   10.37464  39.016897
Age                             0.801833   0.864198   0.432277   1.228879
Age                             1.947308  11.851852   5.043228  44.393241
Age                            89.805269  18.024691  84.149856  15.360983
03.TM                          63.001145          0   6.628242   81.56682
03.TM                           9.851088        100   8.069164   5.222734
03.TM                          14.318442          0   5.763689   7.373272
03.TM                          12.829324          0  79.538905   5.837174
Cluster percentage of drivers   6.884315   6.387509   5.472755   5.133665

                                       8          9         10         11  \
VARIABLE
Day_shift                      94.589552   8.577878  74.747475  91.901408
Day_shift                            0.0  85.553047  17.171717   3.873239
Day_shift                       5.410448   5.869074   8.080808   4.225352
Vehicle_type                    8.768657    4.96614   19.86532   7.746479
Vehicle_type                   73.320896  36.343115        0.0  28.521127
Vehicle_type                    7.089552   9.255079  11.447811  61.971831
Vehicle_type                   10.820896  49.435666  68.686869   1.760563
Gender                                 0  93.905192  11.784512  98.591549
Gender                               0.0        0.0        0.0        0.0
Gender                               100   6.094808  88.215488   1.408451
Age                            76.679104    9.93228   90.23569  19.014085
Age                              2.61194   1.805869   4.713805   5.985915
Age                                  0.0   3.611738   0.673401   60.56338
Age                            20.708955  84.650113   4.377104   14.43662
03.TM                                0.0   4.740406  19.191919   3.521127
03.TM                          70.149254   4.063205        0.0  85.915493
03.TM                                0.0  88.487585  14.478114   8.802817
03.TM                          29.850746   2.708804  66.329966   1.760563
Cluster percentage of drivers   4.226796   3.493415   2.342087   2.239571

                                      12         13         14         15  \
VARIABLE
Day_shift                      12.617702          0        100  89.910314
Day_shift                      82.485876        100          0   6.502242
Day_shift                       4.896422          0          0   3.587444
Vehicle_type                   57.815443        0.0        0.0   8.071749
Vehicle_type                   27.495292  91.777778  86.938776  26.457399
Vehicle_type                    9.227872        0.0        0.0   59.41704
Vehicle_type                    5.461394   8.222222  13.061224   6.053812
Gender                          9.416196  72.222222        100  12.107623
Gender                               0.0        0.0        0.0   0.224215
Gender                         90.583804  27.777778          0  87.892377
Age                             90.39548  99.333333        0.0   9.865471
Age                             0.564972   0.666667   2.040816   3.811659
Age                             3.013183        0.0        0.0   1.121076
Age                             6.026365        0.0  97.959184  84.977578
03.TM                           7.721281        100          0   5.605381
03.TM                           4.708098          0        100   5.156951
03.TM                          81.355932          0          0  80.941704
03.TM                           6.214689          0          0   8.295964
Cluster percentage of drivers   4.187367   3.548616   1.932024   3.517073

                                      16         17       18
VARIABLE
Day_shift                      97.826087          0       60
Day_shift                       1.449275          0       40
Day_shift                       0.724638        100        0
Vehicle_type                         0.0  14.146341      0.0
Vehicle_type                    6.521739   80.97561     97.5
Vehicle_type                   10.144928        0.0      0.0
Vehicle_type                   83.333333   4.878049      2.5
Gender                         98.550725  82.926829      100
Gender                               0.0        0.0        0
Gender                          1.449275  17.073171        0
Age                            34.782609  93.170732        0
Age                            36.231884        0.0        5
Age                             3.623188   6.829268       95
Age                            25.362319        0.0        0
03.TM                          85.507246          0        0
03.TM                           3.623188          0        0
03.TM                           5.797101          0        0
03.TM                           5.072464        100      100
Cluster percentage of drivers   1.088242   1.616592  1.26173

In [577]:
print(new_table_2)

                                      0         1        2         3   \
VARIABLE
Day_shift                       1.000000  1.000000  1.00000  1.000000
Vehicle_type                    1.000000  1.000000  0.00000  0.000000
Gender                          1.000000  1.000000  1.00000  1.000000
Age                             1.000000  0.000000  0.00000  1.000000
03.TM                           0.000000  0.000000  0.00000  0.000000
Cluster percentage of drivers  27.836921  7.791184  3.72999  7.310149

                                     4         5         6         7   \
VARIABLE
Day_shift                      0.000000  1.000000  1.000000  1.000000
Vehicle_type                   1.000000  1.000000  0.000000  1.000000
Gender                         1.000000  1.000000  1.000000  1.000000
Age                            1.000000  0.000000  1.000000  0.000000
03.TM                          0.000000  1.000000  1.000000  1.000000
Cluster percentage of drivers  6.884315  6.387509  5.472755  5.133665

                                     8         9         10        11  \
VARIABLE
Day_shift                      1.000000  1.000000  0.000000  1.000000
Vehicle_type                   0.000000  0.000000  0.000000  0.000000
Gender                         1.000000  1.000000  1.000000  1.000000
Age                            1.000000  1.000000  1.000000  0.000000
03.TM                          0.000000  1.000000  0.000000  1.000000
Cluster percentage of drivers  4.226796  3.493415  2.342087  2.239571

                                     12        13        14        15  \
VARIABLE
Day_shift                      1.000000  1.000000  1.000000  1.000000
Vehicle_type                   0.000000  1.000000  1.000000  0.000000
Gender                         1.000000  0.000000  1.000000  1.000000
Age                            1.000000  1.000000  1.000000  1.000000
03.TM                          1.000000  1.000000  1.000000  1.000000
Cluster percentage of drivers  4.187367  3.548616  1.932024  3.517073

                                     16        17       18
VARIABLE
Day_shift                      1.000000  1.000000  0.00000
Vehicle_type                   1.000000  1.000000  1.00000
Gender                         1.000000  1.000000  1.00000
Age                            0.000000  1.000000  1.00000
03.TM                          1.000000  1.000000  1.00000
Cluster percentage of drivers  1.088242  1.616592  1.26173

In [578]:
print(new_table_3)

                                         0         1        2         3  \
VARIABLE
Day_shift                         1.000000  1.000000  1.00000  1.000000
Vehicle_type                      1.000000  1.000000  0.00000  0.000000
Gender                            1.000000  1.000000  1.00000  1.000000
Age                               1.000000  0.000000  0.00000  1.000000
03.TM                             0.000000  0.000000  0.00000  0.000000
number of significant variables   4.000000  3.000000  2.00000  3.000000
Cluster significance              0.800000  0.600000  0.40000  0.600000
Cluster significant?              1.000000  1.000000  0.00000  1.000000
Cluster percentage of drivers    27.836921  7.791184  3.72999  7.310149
Significant clusters                   NaN       NaN      NaN       NaN

                                        4         5         6         7  \
VARIABLE
Day_shift                        0.000000  1.000000  1.000000  1.000000
Vehicle_type                     1.000000  1.000000  0.000000  1.000000
Gender                           1.000000  1.000000  1.000000  1.000000
Age                              1.000000  0.000000  1.000000  0.000000
03.TM                            0.000000  1.000000  1.000000  1.000000
number of significant variables  3.000000  4.000000  4.000000  4.000000
Cluster significance             0.600000  0.800000  0.800000  0.800000
Cluster significant?             1.000000  1.000000  1.000000  1.000000
Cluster percentage of drivers    6.884315  6.387509  5.472755  5.133665
Significant clusters                  NaN       NaN       NaN       NaN

                                        8         9        10        11  \
VARIABLE
Day_shift                        1.000000  1.000000  0.000000  1.000000
Vehicle_type                     0.000000  0.000000  0.000000  0.000000
Gender                           1.000000  1.000000  1.000000  1.000000
Age                              1.000000  1.000000  1.000000  0.000000
03.TM                            0.000000  1.000000  0.000000  1.000000
number of significant variables  3.000000  4.000000  2.000000  3.000000
Cluster significance             0.600000  0.800000  0.400000  0.600000
Cluster significant?             1.000000  1.000000  0.000000  1.000000
Cluster percentage of drivers    4.226796  3.493415  2.342087  2.239571
Significant clusters                  NaN       NaN       NaN       NaN

                                       12        13        14        15  \
VARIABLE
Day_shift                        1.000000  1.000000  1.000000  1.000000
Vehicle_type                     0.000000  1.000000  1.000000  0.000000
Gender                           1.000000  0.000000  1.000000  1.000000
Age                              1.000000  1.000000  1.000000  1.000000
03.TM                            1.000000  1.000000  1.000000  1.000000
number of significant variables  4.000000  4.000000  5.000000  4.000000
Cluster significance             0.800000  0.800000  1.000000  0.800000
Cluster significant?             1.000000  1.000000  1.000000  1.000000
Cluster percentage of drivers    4.187367  3.548616  1.932024  3.517073
Significant clusters                  NaN       NaN       NaN       NaN

                                       16        17       18  \
VARIABLE
Day_shift                        1.000000  1.000000  0.00000
Vehicle_type                     1.000000  1.000000  1.00000
Gender                           1.000000  1.000000  1.00000
Age                              0.000000  1.000000  1.00000
03.TM                            1.000000  1.000000  1.00000
number of significant variables  4.000000  5.000000  4.00000
Cluster significance             0.800000  1.000000  0.80000
Cluster significant?             1.000000  1.000000  1.00000
Cluster percentage of drivers    1.088242  1.616592  1.26173
Significant clusters                  NaN       NaN      NaN

                                 percentage of significant cluster
VARIABLE
Day_shift                                                      NaN
Vehicle_type                                                   NaN
Gender                                                         NaN
Age                                                            NaN
03.TM                                                          NaN
number of significant variables                                NaN
Cluster significance                                           NaN
Cluster significant?                                           NaN
Cluster percentage of drivers                                  NaN
Significant clusters                                      0.894737

In [579]:
j=[]
for i in range(3, 20):
    j.append(i)
print(j)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]